# Generated by Django 5.2 on 2025-04-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_modelaccuracy_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelaccuracy',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Model Accuracies'},
        ),
        migrations.RenameField(
            model_name='modelaccuracy',
            old_name='date_calculated',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='modelaccuracy',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='modelaccuracy',
            name='mse',
        ),
        migrations.AddField(
            model_name='modelaccuracy',
            name='cryptocurrency',
            field=models.CharField(default='BTC-USD', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelaccuracy',
            name='model_type',
            field=models.CharField(choices=[('SVR', 'Support Vector Regression'), ('LR', 'Linear Regression')], default='SVR', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelaccuracy',
            name='prediction_days',
            field=models.IntegerField(default='10'),
            preserve_default=False,
        ),
    ]
