# Generated by Django 5.2 on 2025-04-08 15:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_modelaccuracy_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelaccuracy',
            options={},
        ),
        migrations.RenameField(
            model_name='modelaccuracy',
            old_name='timestamp',
            new_name='date_calculated',
        ),
        migrations.RemoveField(
            model_name='modelaccuracy',
            name='cryptocurrency',
        ),
        migrations.RemoveField(
            model_name='modelaccuracy',
            name='model_type',
        ),
        migrations.RemoveField(
            model_name='modelaccuracy',
            name='prediction_days',
        ),
        migrations.AddField(
            model_name='modelaccuracy',
            name='model_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelaccuracy',
            name='mse',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
